name: fair-software

on: push

jobs:
  verify:
    name: "fair-software"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out a copy of your repository

      - uses: fair-software/badge@url
        name: Measure compliance with fair-software.eu recommendations
        with:
          MY_REPO_URL: "https://github/com/${{ github.repository }}"
